steps:
  ###
  # Install dependencies
  #
  - name: 'gcr.io/cloud-builders/npm'
    id: install-dependencies
    entrypoint: 'npm'
    args:
      - 'install'
  ###
  # Run cypress tests
  #
  - name: 'cypress/included:12.7.0'
    waitFor: 
      - install-dependencies
    id: run-tests
    entrypoint: 'bash'
    args:
      - '-c'
      - 'npm run cypress:run'